### ISSUE TITLE
Clients can delay shutdown for longer than needed

### ISSUE THREAD

**Issue by ronkorving** [hunterloftis/stoppable#1]
Hi, great work on this module, I like its minimalism and simplicity.

While analyzing the code I noticed that if all in-flight requests finish before the grace period is over, we still wait for the grace timeout to finish. That goes a bit counter to how I would want to setup my HTTP server: a relatively long grace period for big downloads or slow clients, but within reason. Say I am willing to wait up to 30 seconds. If it's relatively quiet on my server, `stoppable` will make me wait the full 30 seconds, even if a single request was in flight for an extra millisecond when `stop` was called.

One solution could be to keep a global connection counter around and `clearTimeout` if it hits 0 during the grace timer.

Thoughts?

**Comment by hunterloftis** [comment]
Thanks for pointing this out! The timeout was holding the process open because I forgot to `unref` it. Just wrote a test validating that and published a fix.

Fixed in v1.0.2.

**Comment by ronkorving** [comment]
Ah right, an unref would do the trick indeed :) As all requests are gone, no events will be pending and the process will shut down. Great work!
