### ISSUE TITLE
Few bugs with current implementation allow Keep-Alive request to sneak in

### ISSUE THREAD

**Issue by raido** [hunterloftis/stoppable#15]
1) https://github.com/hunterloftis/stoppable/blob/master/lib/stoppable.js#L35

_server.close_ should be called before setImmediate, so it happens as soon as possible.
and _"stopped = true"_ should be before setImmediate - so all the requests that complete in current I/O phase would already see that shutdown is initiated.

2) https://github.com/hunterloftis/stoppable/blob/master/lib/stoppable.js#L46

By the time socket.destroy() is called, there might have been already new connections in I/O phase. And since destroy() is called in the end of I/O phase then possibly it is destroying currently active socket with active request. Simply removing the setImmediate and calling _socket.destroy()_ right after _socket.end()_ call should be sufficient.

3) https://github.com/hunterloftis/stoppable/blob/master/lib/stoppable.js#L23 -- after _socket.end()_ should be _socket.destory()_ call.

**Comment by ronkorving** [comment]
@raido 
1. I think so too
2. I'm not sure which line you're now referring to, since master has evolved. Can you confirm if this is still an issue? If (1) is fixed, is this still relevant?
3. Can you confirm if this is still an issue? (I think it is)

**Comment by boneskull** [comment]
seems plausible, but need reproducible cases.

**Comment by raido** [comment]
2. refers to this now in current master -> https://github.com/hunterloftis/stoppable/blob/master/lib/stoppable.js#L62
3. I think is now this - > https://github.com/hunterloftis/stoppable/blob/master/lib/stoppable.js#L33

Case with 3. is that `.end()` will send FIN package but that does not mean that Ngnix for example would actually close the socket right away. So current connection closes but socket is reused for new connection in keep-alive situation. Needs to be confirmed again, it's been a year from original post of this issue.

Overall I could not use this package back then and instead took what I needed and implemented my own solution that suited with my infrastructure setup. I did simulations of thousands of connections, with keep-alive and without to battle test it and that's how I came up with the issue in the first place.

**Comment by raido** [comment]
Once “stopped” flag is set to true, all out going requests should also set header “Connection: close” - so reciving party would know that this connection should be closed. Example Ngnix would then close the connection in Keep Alive scenario.
