### ISSUE TITLE
Probably class deoptimization

### ISSUE THREAD

**Issue by ronkorving** [hunterloftis/stoppable#2]
I've noticed that you're creating a property on every socket. I believe that would cause all these socket objects to be deoptimized. A possible solution that shouldn't impact much I believe would be to change your Set to a Map (also has `forEach`), and use `sockets.set(socket, 0);`, the 0 being the number of pending requests.

Thoughts?

**Comment by hunterloftis** [comment]
Agreed, that's a much cleaner implementation.

Published in v1.0.3.

**Comment by ronkorving** [comment]
Cool 👍
